/****************************************************************************
 * Genesis Plus GX - C++ Menu System
 *
 * menu_cpp.cpp - C++ Menu Implementation
 *
 * Menu system modeled after snes9xGC structure
 ***************************************************************************/

#include "gui.h"
#include "menu_cpp.h"

extern "C" {
#include "../gui/font.h"
#include "../gx_video.h"
#include "../gui_drawing.h"
#include <ogc/video.h>
}

/* External from gx_video.c */
extern "C" {
extern GXRModeObj *vmode;
extern void gxClearScreen(GXColor color);
extern void gxSetScreen();
}

/* External sound data from gx/sounds/ */
extern "C" {
extern const u8 button_over_pcm[];
extern const u32 button_over_pcm_size;
extern const u8 button_select_pcm[];
extern const u32 button_select_pcm_size;
}

/* External image data - generated by Makefile from PNG files */
extern "C" {
extern const u8 Banner_top_png[];
extern const u8 Banner_main_png[];
extern const u8 Banner_bottom_png[];
extern const u8 Button_text_png[];
extern const u8 Button_text_over_png[];
extern const u8 Bg_layer_png[];
}

/**
 * ShowMainMenu
 * 
 * Main entry point for C++ menu system
 * Declared as extern "C" for C linkage (defined in header)
 */
int ShowMainMenu()
{
    return MenuMain();
}

/**
 * MenuMain
 * 
 * Main menu implementation - modeled after snes9xGC
 */
int MenuMain()
{
    int menu = MENU_NONE;
    
    /* Create main window */
    GuiWindow mainWindow(640, 480);
    mainWindow.SetAlignment(ALIGN_LEFT, ALIGN_TOP);
    mainWindow.SetPosition(0, 0);
    
    /* Top banner */
    GuiImageData bannerTopData(Banner_top_png);
    GuiImage bannerTop(&bannerTopData);
    bannerTop.SetAlignment(ALIGN_CENTRE, ALIGN_TOP);
    bannerTop.SetPosition(0, 0);
    mainWindow.Append(&bannerTop);
    
    /* Main logo/banner */
    GuiImageData logoData(Banner_main_png);
    GuiImage logo(&logoData);
    logo.SetAlignment(ALIGN_CENTRE, ALIGN_TOP);
    logo.SetPosition(0, 80);
    mainWindow.Append(&logo);
    
    /* Bottom banner */
    GuiImageData bannerBottomData(Banner_bottom_png);
    GuiImage bannerBottom(&bannerBottomData);
    bannerBottom.SetAlignment(ALIGN_CENTRE, ALIGN_BOTTOM);
    bannerBottom.SetPosition(0, 0);
    mainWindow.Append(&bannerBottom);
    
    /* Create trigger for A button */
    GuiTrigger trigA;
#ifdef HW_RVL
    trigA.SetSimpleTrigger(-1, WPAD_BUTTON_A | WPAD_CLASSIC_BUTTON_A, PAD_BUTTON_A);
#else
    trigA.SetSimpleTrigger(-1, 0, PAD_BUTTON_A);
#endif
    
    /* Create sound effects */
    GuiSound btnSoundOver(button_over_pcm, button_over_pcm_size, SOUND_PCM);
    GuiSound btnSoundClick(button_select_pcm, button_select_pcm_size, SOUND_PCM);
    
    /* Create button images */
    GuiImageData btnImgData(Button_text_png);
    GuiImageData btnImgOverData(Button_text_over_png);
    
    /* Load Game button */
    GuiImage loadGameImg(&btnImgData);
    GuiImage loadGameImgOver(&btnImgOverData);
    GuiText loadGameText("Load Game", 20, (GXColor){255, 255, 255, 255});
    loadGameText.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    loadGameText.SetPosition(0, -2);
    
    GuiButton loadGameBtn(loadGameImg.GetWidth(), loadGameImg.GetHeight());
    loadGameBtn.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    loadGameBtn.SetPosition(-125, -60);
    loadGameBtn.SetImage(&loadGameImg);
    loadGameBtn.SetImageOver(&loadGameImgOver);
    loadGameBtn.SetLabel(&loadGameText);
    loadGameBtn.SetTrigger(&trigA);
    loadGameBtn.SetSoundOver(&btnSoundOver);
    loadGameBtn.SetSoundClick(&btnSoundClick);
    mainWindow.Append(&loadGameBtn);
    
    /* Settings button */
    GuiImage settingsImg(&btnImgData);
    GuiImage settingsImgOver(&btnImgOverData);
    GuiText settingsText("Settings", 20, (GXColor){255, 255, 255, 255});
    settingsText.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    settingsText.SetPosition(0, -2);
    
    GuiButton settingsBtn(settingsImg.GetWidth(), settingsImg.GetHeight());
    settingsBtn.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    settingsBtn.SetPosition(125, -60);
    settingsBtn.SetImage(&settingsImg);
    settingsBtn.SetImageOver(&settingsImgOver);
    settingsBtn.SetLabel(&settingsText);
    settingsBtn.SetTrigger(&trigA);
    settingsBtn.SetSoundOver(&btnSoundOver);
    settingsBtn.SetSoundClick(&btnSoundClick);
    mainWindow.Append(&settingsBtn);
    
    /* Reset button */
    GuiImage resetImg(&btnImgData);
    GuiImage resetImgOver(&btnImgOverData);
    GuiText resetText("Reset", 20, (GXColor){255, 255, 255, 255});
    resetText.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    resetText.SetPosition(0, -2);
    
    GuiButton resetBtn(resetImg.GetWidth(), resetImg.GetHeight());
    resetBtn.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    resetBtn.SetPosition(-125, 20);
    resetBtn.SetImage(&resetImg);
    resetBtn.SetImageOver(&resetImgOver);
    resetBtn.SetLabel(&resetText);
    resetBtn.SetTrigger(&trigA);
    resetBtn.SetSoundOver(&btnSoundOver);
    resetBtn.SetSoundClick(&btnSoundClick);
    mainWindow.Append(&resetBtn);
    
    /* Exit button */
    GuiImage exitImg(&btnImgData);
    GuiImage exitImgOver(&btnImgOverData);
    GuiText exitText("Exit", 20, (GXColor){255, 255, 255, 255});
    exitText.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    exitText.SetPosition(0, -2);
    
    GuiButton exitBtn(exitImg.GetWidth(), exitImg.GetHeight());
    exitBtn.SetAlignment(ALIGN_CENTRE, ALIGN_MIDDLE);
    exitBtn.SetPosition(125, 20);
    exitBtn.SetImage(&exitImg);
    exitBtn.SetImageOver(&exitImgOver);
    exitBtn.SetLabel(&exitText);
    exitBtn.SetTrigger(&trigA);
    exitBtn.SetSoundOver(&btnSoundOver);
    exitBtn.SetSoundClick(&btnSoundClick);
    mainWindow.Append(&exitBtn);
    
    /* Set default focus */
    mainWindow.SetFocus(1);
    loadGameBtn.SetState(STATE_SELECTED);
    
    /* Main menu loop */
    while (menu == MENU_NONE)
    {
        /* Wait for VSync */
        VIDEO_WaitVSync();
        
        /* Update GUI */
        mainWindow.Update(&trigA);
        
        /* Check button states */
        if (loadGameBtn.GetState() == STATE_CLICKED)
        {
            loadGameBtn.ResetState();
            // TODO: Call MenuLoadGame() when implemented
        }
        else if (settingsBtn.GetState() == STATE_CLICKED)
        {
            settingsBtn.ResetState();
            // TODO: Call MenuSettings() when implemented
        }
        else if (resetBtn.GetState() == STATE_CLICKED)
        {
            resetBtn.ResetState();
            // TODO: Implement reset
        }
        else if (exitBtn.GetState() == STATE_CLICKED)
        {
            exitBtn.ResetState();
            menu = MENU_EXIT;
        }
        
        /* Clear screen and draw GUI */
        gxClearScreen((GXColor){0, 0, 0, 255});
        
        /* Draw blue background */
        GUI_DrawRectangle(0, 0, 640, 480, (GXColor){50, 80, 120, 255}, 1);
        
        mainWindow.Draw();
        gxSetScreen();
    }
    
    return menu;
}

/**
 * MenuLoadGame
 * 
 * Load game menu (placeholder for now)
 */
int MenuLoadGame()
{
    /* TODO: Implement file browser */
    /* For now, return to main menu */
    return MENU_EXIT;
}

/**
 * MenuSettings
 * 
 * Settings menu (placeholder for now)
 */
int MenuSettings()
{
    /* TODO: Implement settings browser */
    /* For now, return to main menu */
    return MENU_EXIT;
}
