name: Unit Tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential g++
      
    - name: Build unit tests
      run: |
        cd tests
        make tests
        
    - name: Run unit tests
      run: |
        cd tests
        ./run_tests >> test-results.txt | cat
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/test-results.txt
        retention-days: 5
